<?php
/** Generated by Puja-Route @url: https://github.com/jinnguyen/puja-route */
return array (
  'testadd/key' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\AddRouteController',
    'annotation' => false,
    'action' => 'indexAction',
    'moduleId' => '',
    'controllerId' => 'addroute',
    'actionId' => 'index',
  ),
  'testadd/key/test1' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\AddRouteController',
    'annotation' => false,
    'action' => 'test1Action',
    'moduleId' => '',
    'controllerId' => 'addroute',
    'actionId' => 'test1',
  ),
  'testadd/key/test2' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\AddRouteController',
    'annotation' => false,
    'action' => 'test2Action',
    'moduleId' => '',
    'controllerId' => 'addroute',
    'actionId' => 'test2',
  ),
  '' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Controller\\IndexController',
    'annotation' => false,
    'action' => 'indexAction',
    'moduleId' => '',
    'controllerId' => 'index',
    'actionId' => 'index',
  ),
  'view' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Controller\\IndexController',
    'annotation' => false,
    'action' => 'viewAction',
    'moduleId' => '',
    'controllerId' => 'index',
    'actionId' => 'view',
  ),
  'contact' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Controller\\ContactController',
    'annotation' => false,
    'action' => 'indexAction',
    'moduleId' => '',
    'controllerId' => 'contact',
    'actionId' => 'index',
  ),
  'contact/send' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Controller\\ContactController',
    'annotation' => true,
    'action' => 'Puja\\Route\\Demo\\Action\\Contact\\Send',
    'moduleId' => '',
    'controllerId' => 'contact',
    'actionId' => 'send',
  ),
  'contact/email' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Controller\\ContactController',
    'annotation' => true,
    'action' => 'Puja\\Route\\Demo\\Action\\Contact\\Email',
    'moduleId' => '',
    'controllerId' => 'contact',
    'actionId' => 'email',
  ),
  'contact/email2' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Controller\\ContactController',
    'annotation' => true,
    'action' => 'Puja\\Route\\Demo\\Action\\Contact\\Email2',
    'moduleId' => '',
    'controllerId' => 'contact',
    'actionId' => 'email2',
  ),
  'ajax/send' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\Ajax\\Controller\\IndexController',
    'annotation' => false,
    'action' => 'sendAction',
    'moduleId' => 'ajax',
    'controllerId' => 'index',
    'actionId' => 'send',
  ),
  'ajax/contact' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\Ajax\\Controller\\ContactController',
    'annotation' => false,
    'action' => 'indexAction',
    'moduleId' => 'ajax',
    'controllerId' => 'contact',
    'actionId' => 'index',
  ),
  'ajax' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\Ajax\\Controller\\IndexController',
    'annotation' => true,
    'action' => 'Puja\\Route\\Demo\\Action\\Contact\\Email',
    'moduleId' => 'ajax',
    'controllerId' => 'index',
    'actionId' => 'index',
  ),
  'ajax/contact/send' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\Ajax\\Controller\\ContactController',
    'annotation' => false,
    'action' => 'sendAction',
    'moduleId' => 'ajax',
    'controllerId' => 'contact',
    'actionId' => 'send',
  ),
  'ajax/contact/listcategory' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\Ajax\\Controller\\ContactController',
    'annotation' => false,
    'action' => 'listCategoryAction',
    'moduleId' => 'ajax',
    'controllerId' => 'contact',
    'actionId' => 'listcategory',
  ),
  'news/listing/listing2' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\News\\Controller\\ListingController',
    'annotation' => false,
    'action' => 'listing2Action',
    'moduleId' => 'news',
    'controllerId' => 'listing',
    'actionId' => 'listing2',
  ),
  'news/listing/listing1' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\News\\Controller\\ListingController',
    'annotation' => false,
    'action' => 'listing1Action',
    'moduleId' => 'news',
    'controllerId' => 'listing',
    'actionId' => 'listing1',
  ),
  'product' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\Product\\Controller\\IndexController',
    'annotation' => false,
    'action' => 'indexAction',
    'moduleId' => 'product',
    'controllerId' => 'index',
    'actionId' => 'index',
  ),
  'product/send' => 
  array (
    'controller' => '\\Puja\\Route\\Demo\\Module\\Product\\Controller\\IndexController',
    'annotation' => false,
    'action' => 'sendAction',
    'moduleId' => 'product',
    'controllerId' => 'index',
    'actionId' => 'send',
  ),
);